### ISSUE TITLE
使用后报错classNotFound

### ISSUE THREAD

**Issue by xiaowenjie21** [zhanyingf15/datax-elasticsearch#1]
ERROR JobContainer - Exception when job run
com.alibaba.datax.common.exception.DataXException: Code:[Framework-02], Descript                    ion:[DataX引擎运行过程出错，具体原因请参看DataX运行结束时的错误诊断信息  .].  -                     java.lang.ClassNotFoundException: com.tydic.datax.es.writer.ElasticsearchWriter$                    Job
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.alibaba.datax.core.util.container.LoadUtil.loadPluginClass(LoadUt                    il.java:172)
        at com.alibaba.datax.core.util.container.LoadUtil.loadJobPlugin(LoadUtil                    .java:93)

**Comment by Itmonkeyff** [comment]
请问解决了吗，我也遇到同样的问题，麻烦讲一下

**Comment by ZzzzZzreal** [comment]
> 请问解决了吗，我也遇到同样的问题，麻烦讲一下
这个类不对
![image](https://user-images.githubusercontent.com/32765593/53078873-1a73a680-3530-11e9-9ae8-b88594b60c0c.png)

**Comment by Thanosr** [comment]
想请问下，es作为reader端读取数据的性能有记录吗？
